### ISSUE TITLE
a little guidance

### ISSUE THREAD

**Issue by stredwizard** [escoand/rpi3_codesend#1]
i have some 433 power plugs that work great with codesend but not using the rpi_rf in home assistant so i was very glad when i saw this!

unfortunately i'm struggling, your readme implies just copying the codesend binary and placing in the config directory is enough?

is 433 utilities required which will include the codesend.cpp file and if so where do i put this?

thanks
scott

**Comment by escoand** [comment]
No, you just need the binary file. The cpp file is the source code of this tool and is not needed. But the provided binary is still working with ARM CPUs like RPi.

You write it's working but you ask for guidance, do you have errors?

**Comment by stredwizard** [comment]
Hi and thanks for replying, no I cannot get it working, I copied your configuration in the readme by placing the codesend binary in config/bin and copied your example yaml, replacing your codes with mine of course.

I have a 433 receiver hooked up to my pi, and no codes are received, I also tried from the command line and cannot run codesend (not found) this is why I assumed there was some dependicies missing.

**Comment by stredwizard** [comment]
Also I forget to ask if there is a log of some kind either within home assistant or that I can access using terminal?

**Comment by stredwizard** [comment]
it seems i have made some progress, is it possible to define the pulselength?

**Comment by stredwizard** [comment]
answered my question after finding your reply to another topic, thanks for your help, seems to be working as expected!
